### ISSUE TITLE
Function declaration questions

### ISSUE THREAD

**Issue by TrevorNovak** [Craigspaz/CraigLanguage#6]
I know we discussed using func or def instead of function for function declaration (although I am not totally opposed to the function keyword), however, what are your thoughts on us changing the ; to a : after the function signature to indicate the beginning (scope) of the function body?

**Comment by Craigspaz** [comment]
I am open to that. I only use semi colon now because when I split the lines by a semi colon it would get the line with the function definition all on one line and I can split that apart into its respective components.
